apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
  namespace: default
spec:
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: docker.io/antonosmond491/busybox:0.0.2 # {"$imagepolicy":"flux-system:busybox"}
        command: ["tail", "-f", "/dev/null"]
        terminationGracePeriodSeconds: 0
        resources:
          limits:
            memory: "64Mi"
            cpu: "250m"
